version: '3.8'

services:
  ecommerce:
    image: my-ecommerce-app1
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Database=EcommerceDB;User Id=sa;Password=10203040Medo##;"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "10203040Medo##"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/backup
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "10203040Medo##", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

